seeds:
  - url: https://scp-wiki-cn.wikidot.com/
    scopeType: "prefix"
    exclude:
      - '\?q='
      - '/signin'
      - '\?cid='
      - '/forum'
      - 'timestamp='
      - '/p/'
      - '/shortest-pages-this-month'
      - '/most-recently-created'
      - '/system:'
      - '/search:site'
      - '/feed/'

blockAds: true
blockRules:
  - url: 'ad-delivery\.net'
  - url: 'doubleclick\.net'
  - url: 'btloader\.com'
  - url: 'consent\.nit\.ro'
  - url: 'nitropay\.com'
  - url: 'onesignal\.com'
  - url: 'zh\.xjo\.ch'
  - url: 'dun\.163\.com'
  - url: 'music\.163\.com'
  - url: 'bilibili\.com'
  - url: 'bilivideo\.com'
  - url: 'fbcdn\.net'
  - url: 'vimeocdn\.com'
  - url: 'soundcloud\.com'
  - url: 'scpdb\.org'
  - url: 'avn\.sh'



combineWARC: true
pageLoadTimeout: 30
behaviorTimeout: 40
generateWACZ: true
sitemap: true # 时好时坏
saveState: always
workers: 32
collection: scp-wiki-zh_all
headless: true
lang: zh
logLevel: debug

proxyServer: socks5://host.docker.internal:9909
behaviors: autoscroll,autoplay,autoclick,autofetch,siteSpecific
screenshot: thumbnail
text: final-to-warc